# Generated by Django 6.0.6 on 2026-06-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0003_category_slug_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
